apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ps88uk@gmail.com
    privateKeySecretRef:
      name: cert-issuer
    solvers:
    - http01:
        ingress:
          class:  nginx
