project: default
source:
  repoURL: 'https://github.com/paulsilcock/app-of-apps'
  path: apps
  targetRevision: HEAD
  helm:
    valueFiles:
      - values.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
syncPolicy:
  automated: {}
